'use client';

import { useEffect, useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { createClient } from '@supabase/supabase-js';
import { MessageSquare, Image, Zap, Cloud, ExternalLink } from 'lucide-react';

interface APIUsage {
    openai_chat: number;
    dalle_images: number;
    gemini: number;
    google: number;
}

export function APIUsageBreakdown() {
    const [usage, setUsage] = useState<APIUsage>({
        openai_chat: 0,
        dalle_images: 0,
        gemini: 0,
        google: 0
    });
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadUsage();
    }, []);

    async function loadUsage() {
        try {
            const supabase = createClient(
                process.env.NEXT_PUBLIC_SUPABASE_URL!,
                process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
            );

            // Count blog posts that were AI-generated (OpenAI Chat completions)
            const { count: chatCount } = await supabase
                .from('posts')
                .select('*', { count: 'exact', head: true })
                .in('status', ['drafted', 'published', 'saved', 'approved']);

            // Count posts with AI-generated images (DALL-E)
            const { count: imageCount } = await supabase
                .from('posts')
                .select('*', { count: 'exact', head: true })
                .not('image_path', 'is', null);

            setUsage({
                openai_chat: chatCount || 0,
                dalle_images: imageCount || 0,
                gemini: 0, // Not currently used
                google: 0  // Not currently used
            });
        } catch (e) {
            console.error('Failed to load API usage:', e);
        } finally {
            setLoading(false);
        }
    }

    const total = usage.openai_chat + usage.dalle_images + usage.gemini + usage.google;

    return (
        <div className="grid gap-6">
            <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
                <div className="flex flex-col lg:flex-row items-start lg:items-center justify-between mb-6 gap-4">
                    <div>
                        <h2 className="text-xl font-semibold text-slate-900 flex items-center gap-2">
                            <Zap className="h-5 w-5 text-indigo-600" />
                            API Usage & Costs
                        </h2>
                        <p className="text-sm text-slate-500 mt-1 max-w-2xl">
                            Track the volume of AI operations generated by this application.
                            To view exact costs, credit balances, and billing details, please visit the official OpenAI dashboard.
                        </p>
                    </div>
                    <div className="flex flex-col sm:flex-row items-stretch sm:items-center gap-3 w-full sm:w-auto">
                        <a
                            href="https://platform.openai.com/usage"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="flex items-center justify-center gap-2 px-4 py-2 bg-white hover:bg-slate-50 text-slate-700 border border-slate-200 text-sm font-medium rounded-lg transition-colors shadow-sm"
                        >
                            View API Usage
                            <ExternalLink className="w-4 h-4 ml-1" />
                        </a>
                        <a
                            href="https://platform.openai.com/settings/organization/billing/overview"
                            target="_blank"
                            rel="noopener noreferrer"
                            className="flex items-center justify-center gap-2 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium rounded-lg transition-colors shadow-sm"
                        >
                            View Official Billing
                            <ExternalLink className="w-4 h-4 ml-1" />
                        </a>
                    </div>
                </div>

                {loading ? (
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-4 animate-pulse">
                        <div className="h-24 bg-slate-100 rounded-lg"></div>
                        <div className="h-24 bg-slate-100 rounded-lg"></div>
                        <div className="h-24 bg-slate-100 rounded-lg"></div>
                    </div>
                ) : (
                    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                        <UsageCard
                            label="Total Operations"
                            value={total}
                            subtext="Cumulative AI Tasks"
                            icon={<Zap className="h-5 w-5 text-indigo-600" />}
                            color="indigo"
                        />
                        <UsageCard
                            label="Blog Generations"
                            value={usage.openai_chat}
                            subtext="GPT-4o Chat Completions"
                            icon={<MessageSquare className="h-5 w-5 text-green-600" />}
                            color="green"
                        />
                        <UsageCard
                            label="Image Generations"
                            value={usage.dalle_images}
                            subtext="DALL-E 3 Images Created"
                            icon={<Image className="h-5 w-5 text-purple-600" />}
                            color="purple"
                        />
                        <UsageCard
                            label="Google Search"
                            value={usage.google} // Future Proofing
                            subtext="Search API Calls (Inactive)"
                            icon={<Cloud className="h-5 w-5 text-blue-600" />}
                            color="blue"
                        />
                    </div>
                )}

                <div className="mt-6 bg-slate-50 border border-slate-100 rounded-lg p-4 text-xs text-slate-500 flex flex-col gap-2">
                    <p className="font-semibold text-slate-700">Note on Tracking:</p>
                    <p>
                        This dashboard tracks <strong>local application events</strong> (e.g., successful database records for posts/images).
                        It does not pull real-time token usage from OpenAI, as their API does not expose billing data via standard keys.
                        Discrepancies may occur if operations fail after API calls or if keys are used outside this app.
                    </p>
                </div>
            </div>
        </div>
    );
}

function UsageCard({
    label,
    value,
    subtext,
    icon,
    color
}: {
    label: string;
    value: number;
    subtext: string;
    icon: React.ReactNode;
    color: string;
}) {
    const bgColors: Record<string, string> = {
        indigo: 'bg-indigo-50 border-indigo-100',
        green: 'bg-green-50 border-green-100',
        purple: 'bg-purple-50 border-purple-100',
        amber: 'bg-amber-50 border-amber-100',
        blue: 'bg-blue-50 border-blue-100'
    };

    return (
        <div className={`p-4 rounded-xl border flex flex-col gap-3 ${bgColors[color]} transition-all hover:shadow-sm`}>
            <div className="flex items-center justify-between">
                <span className="text-sm font-medium text-slate-700">{label}</span>
                {icon}
            </div>
            <div>
                <span className="text-2xl font-bold text-slate-900">{value}</span>
                <p className="text-[10px] text-slate-500 mt-1 font-medium">{subtext}</p>
            </div>
        </div>
    );
}
